name: CI - Test Backup Script

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-backup:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bica-backup
      TAG: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create required folders
        run: |
          mkdir -p backups
          mkdir -p pgdata

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .

      - name: Start PostgreSQL container
        run: |
          docker network create bica-net

          docker run -d \
            --name postgres-db \
            --network bica-net \
            -e POSTGRES_USER=myuser \
            -e POSTGRES_PASSWORD=mypass \
            -e POSTGRES_DB=mydatabase \
            -v $(pwd)/pgdata:/var/lib/postgresql/data \
            postgres:15

      - name: Wait for PostgreSQL to be ready
        run: sleep 10

      - name: Run backup script inside container
        run: |
          docker run --rm \
            --network bica-net \
            -e DB_HOST=postgres-db \
            -e DB_PORT=5432 \
            -e DB_USER=myuser \
            -e DB_PASSWORD=mypass \
            -e DB_NAME=mydatabase \
            -e BACKUP_DIR=/mnt/backups \
            -e RETENTION_DAYS=7 \
            -e ENCRYPT=false \
            -v $(pwd)/backups:/mnt/backups \
            $IMAGE_NAME:$TAG /backup.sh

      - name: Show backup results
        run: ls -lh backups
